use crate::parse::{InnerGlobalComponent, PropertyField, RouteMacroAttr};
use proc_macro2::TokenStream;
use quote::{format_ident, quote, IdentFragment};
use syn::{parse_macro_input, Ident, ItemEnum};

mod parse;

/// Attribute used on `NavRoute` enum.
///
/// This macro generates:
/// - Sub-enum which implements [`Route::Kind`][stern::Route::Kind]
/// - `Into<ui::NavRoute>` implementation for `NavRoute`
/// - Re-exports for types generated by [`adopter`] attribute, based on its name
/// - `ViewModelOwner` which owns all viewmodels
///
/// Since the macro re-exports types from `slint_generated<YourWindow>` module, it
/// must be used in the same module as which you call [`slint::include_modules!`].
///
/// If your adopter's name is `XxxAdopter`, the variant should be `Xxx`.
///
/// ## Options
/// - slint_type: Route enum type in your slint file. default value: `UiNavRoute`
#[proc_macro_attribute]
pub fn route(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let item: ItemEnum = parse_macro_input!(item);
    let attr: RouteMacroAttr = parse_macro_input!(attr);
    let item_name = &item.ident;
    let slint_typ_name = attr.slint_type_name;

    let kind_enum_name = format_ident!("{}Kind", item_name);

    let re_exports = {
        let typs = item.variants.iter().map(|v| {
            let vm_trait_name = viewmodel_trait_ident(&v.ident);
            let states_struct_name = state_struct_ident(&v.ident);
            quote! {
                #vm_trait_name, #states_struct_name,
            }
        });
        quote! {
            pub use self::slint_generatedAppWindow::{
                #(#typs)*
            };
        }
    };
    let item_with_attr = quote! {
        #[derive(stern::re_exports::EnumDiscriminants)]
        #[strum_discriminants(name(#kind_enum_name), derive(stern::re_exports::EnumIter, Hash))]
        #item
    };
    let into_impl = {
        let match_arms = item.variants.iter().map(|v| {
            let ident = &v.ident;
            quote! {
                Self::#ident => #slint_typ_name::#ident,
            }
        });
        quote! {
            impl Into<#slint_typ_name> for #kind_enum_name {
                fn into(self) -> #slint_typ_name {
                    match self {
                        #(#match_arms)*
                    }
                }
            }
        }
    };
    let kind_impl = {
        quote! {
            impl #item_name {
                pub fn kind(&self) -> #kind_enum_name {
                    self.into()
                }
            }
        }
    };
    let route_enum_impl = {
        quote! {
            impl stern::nav::RouteEnum for #item_name {
                type Kind = #kind_enum_name;
                type SlintKind = #slint_typ_name;
            }
        }
    };
    quote! {
        #item_with_attr

        #into_impl

        #kind_impl

        #route_enum_impl

        #re_exports
    }
    .into()
}

/// Attribute used on generated `InnerXxxAdopter` type.
///
/// This macro generates:
/// - `XxxScreenStates`, which contains [`PropertyHandle`]s for each properties
/// - `XxxViewModelTrait`, which contains each callback to be implemented
#[proc_macro_attribute]
pub fn adopter(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let item = parse_macro_input!(item as InnerGlobalComponent);
    adopter_inner(attr.into(), item).into()
}

fn adopter_inner(_attr: TokenStream, item: InnerGlobalComponent) -> TokenStream {
    let viewmodel_trait_name = viewmodel_trait_ident(&item.name);

    let state_struct = generate_state_struct(&item.name, &item.properties);
    let viewmodel_trait = {
        let callbacks = item.callbacks.iter().map(|f| {
            let fn_name = format_ident!("on_{}", &f.ident);
            let args = f.arg_type.elems.iter().enumerate().map(|(idx, typ)| {
                let arg_name = format_ident!("args_{}", idx);
                quote! {
                    #arg_name: #typ,
                }
            });
            let ret_typ = &f.ret_type;
            quote! {
                fn #fn_name(&mut self, #(#args)*) -> #ret_typ;
            }
        });

        quote! {
            pub trait #viewmodel_trait_name {
                #(#callbacks)*
            }
        }
    };
    let regiter_impl = {
        let public_global_name = public_global_ident(&item.name);

        let registerations = item.callbacks.iter().map(|cb| {
            let method_name = format_ident!("on_{}", cb.ident);
            let args = cb
                .arg_type
                .elems
                .iter()
                .enumerate()
                .map(|(idx, _ty)| format_ident!("arg_{}", idx));
            let args = quote! {
                #(#args),*
            };
            quote! {
                self.#method_name({
                    let vm_clone = std::rc::Rc::clone(&vm);
                    move |#args| {
                        vm_clone.borrow_mut().#method_name(#args)
                    }
                });
            }
        });

        quote! {
            impl<VMImpl> stern::GlobalExt<VMImpl> for #public_global_name<'_>
                where VMImpl: #viewmodel_trait_name + 'static {
                fn register_viewmodel(&self, vm: std::rc::Rc<core::cell::RefCell<VMImpl>>){
                    #(#registerations)*
                }
            }
        }
    };
    let original = item.original;
    quote! {
        #original

        #state_struct

        #viewmodel_trait

        #regiter_impl
    }
}

fn generate_state_struct(base: &str, properties: &Vec<PropertyField>) -> TokenStream {
    let state_struct_name = state_struct_ident(base);
    let public_global_name = public_global_ident(base);
    let state_struct_def = {
        let fields = properties.iter().map(|f| {
            let field_name = &f.ident;
            let field_ty = &f.ty;
            quote! {
                pub #field_name: stern::PropertyHandle<#field_ty>,
            }
        });

        quote! {
            #[derive(Debug)]
            pub struct #state_struct_name {
                #(#fields)*
            }
        }
    };
    let state_struct_impl = {
        let field_impls = properties.iter().map(|f| {
            let field_name = &f.ident;
            let get_method_name = format_ident!("get_{}", &f.ident);
            let set_method_name = format_ident!("set_{}", &f.ident);
            quote! {
                #field_name: stern::PropertyHandle::new(
                    {
                        let adopter_weak = adopter_weak.clone();
                        move || {
                            let adopter_strong = adopter_weak.unwrap();
                            adopter_strong.#get_method_name()
                        }
                    },
                    {
                        let adopter_weak = adopter_weak.clone();
                        move |val| {
                            let adopter_strong = adopter_weak.unwrap();
                            adopter_strong.#set_method_name(val)
                        }
                    },
                ),
            }
        });
        quote! {
            impl #state_struct_name {
                pub fn new(adopter_weak: slint::Weak<#public_global_name<'static>>) -> Self {
                    Self {
                        #(#field_impls)*
                    }
                }
            }
        }
    };
    quote! {
        #state_struct_def

        #state_struct_impl
    }
}

fn state_struct_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}States", base)
}

fn viewmodel_trait_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}ViewModelTrait", &base)
}

fn public_global_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}Adopter", &base)
}
