use crate::parse::{InnerGlobalComponent, RouteMacroAttr};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{ItemEnum, parse_macro_input};

mod parse;

/// Attribute used on `NavRoute` enum.
///
/// This macro generates:
/// - Sub-enum which implements [`Route::Kind`][slint_fw::Route::Kind]
/// - `Into<ui::NavRoute>` implementation for `NavRoute`
/// - Re-exports for types generated by [`adopter`] attribute, based on its name
///
/// Since the macro re-exports types from `slint_generated<YourWindow>` module, it
/// must be used in the same module as which you call [`slint::include_modules!`].
///
/// If your adopter's name is `XxxAdopter`, the variant should be `Xxx`.
///
/// ## Options
/// - slint_type: Route enum type in your slint file. default value: `UiNavRoute`
#[proc_macro_attribute]
pub fn route(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let item: ItemEnum = parse_macro_input!(item);
    let attr: RouteMacroAttr = parse_macro_input!(attr);
    let item_name = &item.ident;
    let slint_typ_name = attr.slint_type_name;

    let kind_enum_name = format_ident!("{}Kind", item_name);

    let re_exports = {
        let typs = item.variants.iter().map(|v| {
            let vm_trait_name = format_ident!("{}ViewModelTrait", &v.ident);
            let states_struct_name = format_ident!("{}States", &v.ident);
            quote! {
                #vm_trait_name, #states_struct_name,
            }
        });
        quote! {
            pub use self::slint_generatedAppWindow::{
                #(#typs)*
            };
        }
    };
    let item_with_attr = quote! {
        #[derive(slint_fw::re_exports::EnumDiscriminants)]
        #[strum_discriminants(name(#kind_enum_name), derive(slint_fw::re_exports::EnumIter, Hash))]
        #item
    };
    let into_impl = {
        let match_arms = item.variants.iter().map(|v| {
            let ident = &v.ident;
            quote! {
                Self::#ident => #slint_typ_name::#ident,
            }
        });
        quote! {
            impl Into<#slint_typ_name> for #kind_enum_name {
                fn into(self) -> #slint_typ_name {
                    match self {
                        #(#match_arms)*
                    }
                }
            }
        }
    };
    let kind_impl = {
        quote! {
            impl #item_name {
                pub fn kind(&self) -> #kind_enum_name {
                    self.into()
                }
            }
        }
    };
    let route_enum_impl = {
        quote! {
            impl slint_fw::nav::RouteEnum for #item_name {
                type Kind = #kind_enum_name;
                type SlintKind = #slint_typ_name;
            }
        }
    };
    quote! {
        #item_with_attr

        #into_impl

        #kind_impl

        #route_enum_impl

        #re_exports
    }
    .into()
}

/// Attribute used on generated `InnerXxxAdopter` type.
///
/// This macro generates:
/// - `XxxScreenStates`, which contains [`PropertyHandle`]s for each properties
/// - `XxxViewModelTrait`, which contains each callback to be implemented
#[proc_macro_attribute]
pub fn adopter(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let item = parse_macro_input!(item as InnerGlobalComponent);
    adopter_inner(attr.into(), item).into()
}

fn adopter_inner(_attr: TokenStream, item: InnerGlobalComponent) -> TokenStream {
    let state_struct_name = format_ident!("{}States", &item.name);
    let viewmodel_trait_name = format_ident!("{}ViewModelTrait", &item.name);

    /*let set_callback_handlers = item.callbacks.into_iter().map(|f| {
        let callback_field_name = f.ident;
        let vm_callback_name = format_ident!("on_{}", &callback_field_name);

        quote! {
            let _self = self.0.as_ref();
            #[allow(unused)]
            { *&#inner_adopter_name::FIELD_OFFSETS.#callback_field_name() }
                .apply_pin(_self)
                .set_handler(move |args| #vm_callback_name());
            { *&InnerConnectionFailedAdopter::FIELD_OFFSETS.callback_tracker_retry_connection() }
                .apply_pin(_self)
                .mark_dirty();
        }
    });*/
    let state_struct = generate_state_struct(&item.name, &item.properties);
    let viewmodel_trait = {
        let callbacks = item.callbacks.into_iter().map(|f| {
            let fn_name = format_ident!("on_{}", &f.ident);
            let args = f.arg_type.elems.iter().enumerate().map(|(idx, typ)| {
                let arg_name = format_ident!("args_{}", idx);
                quote! {
                    #arg_name: #typ,
                }
            });
            let ret_typ = f.ret_type;
            quote! {
                fn #fn_name(#(#args)*) -> #ret_typ;
            }
        });

        quote! {
            pub trait #viewmodel_trait_name {
                #(#callbacks)*
            }
        }
    };
    /*quote! {
        impl<'a> #inner_adopter_name<'a> {
            pub fn into_state_and_viewmodel(
                self,
                vm: impl #vm_name,
            ) -> {
                // loop over callback fields
                #(#set_callback_handlers)*
            }
        }
    }*/
    let original = item.original;
    quote! {
        #original

        #state_struct

        #viewmodel_trait

        #regiter_impl
    }
}

fn generate_state_struct(base: &str, properties: &Vec<PropertyField>) -> TokenStream {
    let state_struct_name = state_struct_ident(base);
    let public_global_name = public_global_ident(base);
    let state_struct_def = {
        let fields = properties.iter().map(|f| {
            let field_name = &f.ident;
            let field_ty = &f.ty;
            quote! {
                pub #field_name: slint_fw::PropertyHandle<#field_ty>,
            }
        });

        quote! {
            #[derive(Debug)]
            pub struct #state_struct_name {
                #(#fields)*
            }
        }
    };
    let state_struct_impl = {
        let field_impls = properties.iter().map(|f| {
            let field_name = &f.ident;
            let get_method_name = format_ident!("get_{}", &f.ident);
            let set_method_name = format_ident!("set_{}", &f.ident);
            quote! {
                #field_name: slint_fw::PropertyHandle::new(
                    {
                        let adopter_weak = adopter_weak.clone();
                        move || {
                            let adopter_strong = adopter_weak.unwrap();
                            adopter_strong.#get_method_name()
                        }
                    },
                    {
                        let adopter_weak = adopter_weak.clone();
                        move |val| {
                            let adopter_strong = adopter_weak.unwrap();
                            adopter_strong.#set_method_name(val)
                        }
                    },
                ),
            }
        });
        quote! {
            impl #state_struct_name {
                pub fn new(adopter_weak: slint::Weak<#public_global_name<'static>>) -> Self {
                    Self {
                        #(#field_impls)*
                    }
                }
            }
        }
    };
    quote! {
        #state_struct_def

        #state_struct_impl
    }
}

fn state_struct_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}States", base)
}

fn viewmodel_trait_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}ViewModelTrait", &base)
}

fn public_global_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}Adopter", &base)
}

fn public_global_ext_trait_ident(base: impl IdentFragment) -> Ident {
    format_ident!("{}AdopterExt", base)
}
